# Generated by Django 6.0 on 2026-03-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_price_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='margin_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Auto-calculated %', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_percentage',
            field=models.DecimalField(choices=[(0.0, '0%'), (5.0, '5%'), (12.0, '12%'), (18.0, '18%'), (28.0, '28%')], decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('nos', 'Numbers (Nos)'), ('ml', 'Milliliters (ml)'), ('ltr', 'Liters (Ltr)'), ('g', 'Grams (g)'), ('kg', 'Kilograms (kg)')], default='nos', max_length=10),
        ),
    ]
