# Generated by Django 6.0 on 2026-03-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_alert',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Alert when stock falls below this', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current stock on hand', max_digits=10),
        ),
    ]
