# Generated by Django 6.0 on 2026-03-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_inventoryitem_is_active_batch_wastagelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='current_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='initial_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='low_stock_alert_level',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_stock_alert',
            field=models.IntegerField(default=5, help_text='Alert when stock falls below this'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='Current stock on hand'),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wastagelog',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
