# Generated by Django 6.0 on 2026-03-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_batch_current_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='enable_packet_selling',
            field=models.BooleanField(default=False, help_text='Allow selling in packets'),
        ),
        migrations.AddField(
            model_name='product',
            name='packet_label',
            field=models.CharField(default='Packet', help_text='Label for the packet unit (e.g., Pkt, Box, Dozen)', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='packet_selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price when selling a full packet', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='packet_size',
            field=models.IntegerField(default=1, help_text='How many nos per packet (e.g., 10 candies = 1 pkt)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='Current stock on hand (in base unit)'),
        ),
    ]
