# Generated by Django 6.0 on 2026-03-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_saleitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='quantity_added',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
