# Generated by Django 6.0 on 2026-03-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_purchase_quantity_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='sell_unit',
            field=models.CharField(choices=[('nos', 'Nos'), ('pkt', 'Packet')], default='nos', max_length=10),
        ),
    ]
