# Generated by Django 6.0 on 2026-03-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_saleitem_sell_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='transportation_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
