# Generated by Django 6.0 on 2026-03-23 16:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sales', '0009_purchase_transportation_charge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Electricity', 'Electricity & Utilities'), ('Salary', 'Staff Salaries'), ('Rent', 'Shop Rent'), ('Transportation', 'Transportation & Logistics'), ('Maintenance', 'Equipment Maintenance'), ('Packaging', 'Packaging Materials'), ('Other', 'Other Expenses')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, help_text='E.g., Electricity bill for March', null=True)),
                ('bakery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.bakery')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
